M48
; DRILL file {KiCad (6.0.7)} date Tue Sep  6 17:39:22 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-06T17:39:22+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0709
%
G90
G05
T1
X4.3701Y-5.6791
X4.7244Y-5.6791
X4.9606Y-5.6791
X5.315Y-5.6791
T0
M30
